openapi: 3.1.0
info:
  title: OTP Verification
  version: 1.0.0
servers:
  - url: https://example.com  # 🔁 Replace with your actual API base URL
paths:
  /send_otp:
    post:
      operationId: sendOTP
      summary: Send OTP to Telegram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: string
                  description: Telegram chat ID of the recipient
      responses:
        '200':
          description: OTP sent successfully
  /verify_otp:
    post:
      operationId: verifyOTP
      summary: Verify OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: string
                  description: Telegram chat ID of the recipient
                otp:
                  type: string
                  description: One-Time Password to verify
      responses:
        '200':
          description: OTP verified successfully
        '401':
          description: Invalid or expired OTP
