openapi: 3.1.0
info:
  title: Telegram Bot API Integration
  version: 1.0.0
servers:
  - url: https://api.telegram.org/bot7556260353:AAEM_qHgLpMpRT6qeFbpegv63apG3-KzSXU
paths:
  /sendMessage:
    post:
      operationId: sendMessage
      summary: Send a message via Telegram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: integer
                  description: Unique identifier for the target chat
                text:
                  type: string
                  description: Text of the message to be sent
      responses:
        '200':
          description: Message sent successfully
